allprojects {
    group = project.group
    version = project.version
}

subprojects {
    apply plugin: 'java-library'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(project.javaVersion)
        }
    }

    tasks.withType(Jar).configureEach {
        archiveBaseName = "interlink-${project.name}"
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Javadoc).configureEach {
        options.encoding = 'UTF-8'
    }

    if (file('src/main/java').exists()) {
        tasks.register('javadocJar', Jar) {
            archiveClassifier = 'javadoc'
            from tasks.named('javadoc')
        }

        tasks.register('sourcesJar', Jar) {
            archiveClassifier = 'sources'
            from sourceSets.main.allJava
        }

        tasks.named('assemble') {
            dependsOn tasks.named('javadocJar'), tasks.named('sourcesJar')
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    dependencies {
        testImplementation "org.junit.jupiter:junit-jupiter:${project.junitVersion}"
    }
}